version: '3'
services:
  server:
    build: ./server
    volumes:
      - ./server:/usr/src/app/server
    ports:
      - 3000:3000
    links:
      - db
  db:
    image: mongo:3.2.21-jessie
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password,
    ports:
      - 27017:27017
  # client:
  #   build: ./client
  #   volumes: 
  #     - ./client:/usr/src/app/client
  #   ports:
  #     - 8080:8080